services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    depends_on:
      - mongo
      
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db

